export const STANDARD_EVENT_NAMES_V0 = [
  'checkout_completed',
  'checkout_started',
  'collection_view',
  'page_view',
  'payment_info_submitted',
  'product_added_to_cart',
  'product_view',
  'performed_search',
] as const;

export type StandardEventNameV0 = typeof STANDARD_EVENT_NAMES_V0[number];

// Code generated by jtd-codegen for TypeScript v0.2.1

export type StandardEventsV0 =
  | StandardEventsV0CheckoutCompleted
  | StandardEventsV0CheckoutStarted
  | StandardEventsV0CollectionView
  | StandardEventsV0PageView
  | StandardEventsV0PaymentInfoSubmitted
  | StandardEventsV0PerformedSearch
  | StandardEventsV0ProductAddedToCart
  | StandardEventsV0ProductView;

export interface StandardEventsV0CheckoutCompleted {
  event_name: 'checkout_completed';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0CheckoutStarted {
  event_name: 'checkout_started';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0CollectionView {
  event_name: 'collection_view';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0PageView {
  event_name: 'page_view';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0PaymentInfoSubmitted {
  event_name: 'payment_info_submitted';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0PerformedSearch {
  event_name: 'performed_search';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0ProductAddedToCart {
  event_name: 'product_added_to_cart';
  event_schema_version: string;
  page_url: string;
}

export interface StandardEventsV0ProductView {
  event_name: 'product_view';
  event_schema_version: string;
  page_url: string;
}
