api_version = "2026-04"

[[extensions]]
name = "My checkout extension"
handle = "checkout-ui"
uid = "fddfc370-27c7-c30f-4ee0-a927194e2accadefd40c"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.actions.render-before"
module = "./Actions.jsx"

[[extensions.targeting]]
target = "purchase.checkout.delivery-address.render-before"
module = "./Delivery.jsx"

[[extensions.targeting]]
target = "purchase.checkout.shipping-option-list.render-after"
module = "./ShippingOptions.jsx"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./Block.jsx"
