api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Print Tutorial"
handle = "print-tutorial"
uid = "ccf7edf4-a12d-b60a-9d4a-1cb8691864d6ec6a83e2"
description = "POS UI extension print tutorial"

[[extensions.targeting]]
module = "./src/HomeTile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/HomeModal.tsx"
target = "pos.home.modal.render"

