// Code generated by jtd-codegen for TypeScript v0.2.1

export type StandardEventsV1 =
  | StandardEventsV1CheckoutCompleted
  | StandardEventsV1CheckoutStarted
  | StandardEventsV1CollectionViewed
  | StandardEventsV1PageViewed
  | StandardEventsV1PaymentInfoSubmitted
  | StandardEventsV1ProductAddedToCart
  | StandardEventsV1ProductVariantViewed
  | StandardEventsV1ProductViewed
  | StandardEventsV1SearchSubmitted;

export interface StandardEventsV1CheckoutCompleted {
  event_name: 'checkout_completed';
  checkout_id: number;
  discount_code: string;
  email_sha256: string;
  order_id: number;
  phone_sha256: string;
  products: Product[];
  shipping_price: number;
  subtotal_price: number;
  tax_price: number;
  total_price: number;
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1CheckoutStarted {
  event_name: 'checkout_started';
  products: Product[];
  total_price: number;
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1CollectionViewed {
  event_name: 'collection_viewed';
  collection_title: string;
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1PageViewed {
  event_name: 'page_viewed';
  event_id?: string;
  event_schema_version?: string;
  page_referrer?: string;
  page_title?: string;
  page_url?: string;
}

export interface StandardEventsV1PaymentInfoSubmitted {
  event_name: 'payment_info_submitted';
  currency: string;
  total_price: number;
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1ProductAddedToCart {
  event_name: 'product_added_to_cart';
  products: Product[];
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1ProductVariantViewed {
  event_name: 'product_variant_viewed';
  products: Product[];
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1ProductViewed {
  event_name: 'product_viewed';
  products: Product[];
  event_id?: string;
  event_schema_version?: string;
}

export interface StandardEventsV1SearchSubmitted {
  event_name: 'search_submitted';
  search_query: string;
  event_id?: string;
  event_schema_version?: string;
}

export interface Product {
  collection_title: string;
  currency: string;
  product_gid: string;
  product_id: number;
  product_title: string;
  product_vendor: string;
  quantity: number;
  variant_id: number;
  variant_price: number;
  variant_sku: string;
  variant_title: string;
}
