name: app-extension-libs

type: node

up:
  - git_hooks:
      commit-msg: ./scripts/commitlint.sh
      pre-commit: ./scripts/prettier.sh
  - railgun
  - node:
      version: v12.11.1
      yarn: true
      packages:
        - .

commands:
  build: yarn run build
  console: node
  new-component: node ./scripts/new-component
  new-extension-input: node ./scripts/new-extension-input
  nuke: yarn run clean && rm -rf ./node_modules
  server: yarn run server
  test: yarn run test
  build-consumer: yarnpkg build && ./scripts/build-consumer.sh
  restore-consumer: ./scripts/restore-consumer.sh

open:
  app: https://app-extension-libs.myshopify.io
