// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Context {
  /**
   * TODO
   */
  document: WebPixelsDocument;

  /**
   * TODO
   */
  navigator: WebPixelsNavigator;

  /**
   * TODO
   */
  window: WebPixelsWindow;
}

export interface Connection {
  /**
   * TODO
   */
  downlink: number;

  /**
   * TODO
   */
  downlinkMax: number;

  /**
   * TODO
   */
  effectiveType: string;

  /**
   * TODO
   */
  rtt: number;

  /**
   * TODO
   */
  saveData: boolean;

  /**
   * TODO
   */
  type: string;
}

export interface Location {
  /**
   * TODO
   */
  hash: string;

  /**
   * TODO
   */
  host: string;

  /**
   * TODO
   */
  hostname: string;

  /**
   * TODO
   */
  href: string;

  /**
   * TODO
   */
  origin: string;

  /**
   * TODO
   */
  pathname: string;

  /**
   * TODO
   */
  port: string;

  /**
   * TODO
   */
  protocol: string;

  /**
   * TODO
   */
  search: string;
}

export interface NavigatorUadata {
  /**
   * TODO
   */
  brands: string[];

  /**
   * TODO
   */
  mobile: boolean;

  /**
   * TODO
   */
  platform: string;
}

export interface WebPixelsDocument {
  /**
   * TODO
   */
  characterSet: string;

  /**
   * TODO
   */
  documentURI: string;

  /**
   * TODO
   */
  hidden: boolean;

  /**
   * TODO
   */
  lastModified: string;

  /**
   * TODO
   */
  location: Location;

  /**
   * TODO
   */
  readyState: string;

  /**
   * TODO
   */
  title: string;

  /**
   * TODO
   */
  visibilityState: string;
}

export interface WebPixelsNavigator {
  /**
   * TODO
   */
  cookieEnabled: boolean;

  /**
   * TODO
   */
  hardwareConcurrency: number;

  /**
   * TODO
   */
  language: string;

  /**
   * TODO
   */
  languages: readonly string[];

  /**
   * TODO
   */
  maxTouchPoints: number;

  /**
   * TODO
   */
  onLine: boolean;

  /**
   * TODO
   */
  pdfViewerEnabled: boolean;

  /**
   * TODO
   */
  userAgent: string;

  /**
   * TODO
   */
  webdriver: boolean;
}

export interface WebPixelsWindow {
  /**
   * TODO
   */
  innerHeight: number;

  /**
   * TODO
   */
  innerWidth: number;

  /**
   * TODO
   */
  location: Location;

  /**
   * TODO
   */
  origin: string;

  /**
   * TODO
   */
  outerHeight: number;

  /**
   * TODO
   */
  outerWidth: number;

  /**
   * TODO
   */
  pageXOffset: number;

  /**
   * TODO
   */
  pageYOffset: number;

  /**
   * TODO
   */
  screenX: number;

  /**
   * TODO
   */
  screenY: number;

  /**
   * TODO
   */
  scrollX: number;

  /**
   * TODO
   */
  scrollY: number;

  /**
   * TODO
   */
  userAgent: string;
}
