import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs';
import {
  generateCodeBlock,
  generateTSXCodeBlock,
} from '../helpers/generateCodeBlock';

const generateCodeBlockForPrintApi = (title: string, fileName: string) =>
  generateCodeBlock(title, 'print-api', fileName);

const data: ReferenceEntityTemplateSchema = {
  name: 'Print API',
  description:
    'The Print API enables document printing functionality in your POS UI extension. Use this API to trigger the native print dialog for your documents.' +
    '\n\nSupported document types:' +
    '\n\n- **HTML documents** (`.html`, `.htm`) - Best printing experience with full CSS styling, embedded images, and complex layouts. Use for receipts, invoices, and formatted reports.' +
    '\n- **Text files** (`.txt`, `.csv`) - Plain text with basic content and tabular data support. Use for simple receipts and data exports.' +
    '\n- **Image files** (`.png`, `.jpg`, `.jpeg`, `.gif`, `.bmp`, `.webp`) - Common web formats with format-specific optimizations. Use for logos, charts, QR codes, and barcodes.' +
    '\n- **PDF files** (`.pdf`) - Behavior varies by platform: prints directly on iOS/desktop, but downloads to external viewer on Android. Use for complex documents and compliance requirements.',
  isVisualComponent: false,
  type: 'APIs',
  definitions: [
    {
      title: 'Properties',
      description:
        'The `PrintApi` object provides properties for triggering document printing. Access these properties through `api.print` to initiate print operations with various document types.',
      type: 'PrintApiContent',
    },
  ],
  category: 'Target APIs',
  subCategory: 'Platform APIs',
  related: [],
  examples: {
    description:
      'Learn how to trigger print operations for documents, receipts, and reports using various file formats and URL types.',
    examples: [
      {
        codeblock: generateCodeBlockForPrintApi(
          'Print a document from a tile',
          'print',
        ),
        description:
          'Trigger the native print dialog directly from a tile interaction. This example demonstrates using `api.print()` to initiate printing from a tile tap, enabling quick access to print functionality for receipts, reports, or other documents without requiring modal navigation.',
      },
      {
        codeblock: generateTSXCodeBlock(
          'Print using a relative file path',
          'print-api',
          'print-relative',
        ),
        description:
          'Print documents using relative file paths within your extension. This example shows how to use `api.print()` with relative URLs to access documents bundled with your extension, ideal for printing static templates, pre-formatted receipts, or embedded resources.',
      },
      {
        codeblock: generateTSXCodeBlock(
          'Print using an external URL',
          'print-api',
          'print-full-url',
        ),
        description:
          'Print documents from external URLs or dynamically generated content. This example demonstrates using `api.print()` with full URLs to print documents hosted externally or generated by your backend, supporting dynamic receipts, invoices, or reports with real-time data.',
      },
    ],
  },

  subSections: [
    {
      type: 'Generic',
      anchorLink: 'best-practices',
      title: 'Best practices',
      sectionContent: `\n- **Handle printing errors gracefully:** Implement proper error handling for print operations, including network failures, unsupported document types, or printer connectivity issues.\n- **Optimize documents for printing:** Design your printable documents with appropriate sizing, margins, and formatting that work well with printers and standard paper sizes.\n- **Provide user feedback:** Give users clear feedback about print operations, including loading states, success confirmations, and error messages when printing fails.\n`,
    },
    {
      type: 'Generic',
      anchorLink: 'limitations',
      title: 'Limitations',
      sectionContent: `\n- PDF printing on Android devices requires downloading the file and using an external application, which may interrupt the user workflow.\n- Print operations depend on device printer connectivity and configuration, which may not be available in all POS setups.\n- Document formatting and appearance may vary depending on the printer type, paper size, and device capabilities.\n`,
    },
  ],
};

export default data;
