api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Subscription Tutorial"
handle = "subscription-tutorial"
description = "POS UI extension subscription tutorial"

[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"
