api_version = "2025-10"

# [START toml.description]
[[extensions]]
type = "ui_extension"
name = "Subscription Tutorial"
handle = "subscription-tutorial"
description = "POS UI extension subscription tutorial"
# [END toml.description]

[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"

# [START toml.optional_targets]
# Optional additional targets for line item details screen
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.cart.line-item-details.action.render"

[[extensions.targeting]]
module = "./src/MenuItem.jsx"
target = "pos.cart.line-item-details.action.menu-item.render"
# [END toml.optional_targets]
