export interface Denylist {
  [key: string]: boolean | (() => any);
}

export const builtIns: Denylist = {
  // Browser
  AbortController: true,
  AbortSignal: true,
  BackgroundFetchManager: true,
  BackgroundFetchRecord: true,
  BackgroundFetchRegistration: true,
  BarcodeDetector: true,
  BroadcastChannel: true,
  ByteLengthQueuingStrategy: true,
  CSSSkewX: true,
  CSSSkewY: true,
  Cache: true,
  CacheStorage: true,
  CanvasGradient: true,
  CanvasPattern: true,
  CompressionStream: true,
  Crypto: true,
  CryptoKey: true,
  DOMException: true,
  DOMMatrix: true,
  DOMMatrixReadOnly: true,
  DOMPoint: true,
  DOMPointReadOnly: true,
  DOMQuad: true,
  DOMRect: true,
  DOMRectReadOnly: true,
  DOMStringList: true,
  DecompressionStream: true,
  EventSource: true,
  File: true,
  FileList: true,
  FileReader: true,
  FileReaderSync: true,
  IDBCursor: true,
  IDBCursorWithValue: true,
  IDBDatabase: true,
  IDBFactory: true,
  IDBIndex: true,
  IDBKeyRange: true,
  IDBObjectStore: true,
  IDBOpenDBRequest: true,
  IDBRequest: true,
  IDBTransaction: true,
  IDBVersionChangeEvent: true,
  ImageBitmapRenderingContext: true,
  Lock: true,
  LockManager: true,
  MediaCapabilities: true,
  NavigationPreloadManager: true,
  NetworkInformation: true,
  Notification: true,
  OffscreenCanvas: true,
  OffscreenCanvasRenderingContext2D: true,
  Path2D: true,
  PaymentInstruments: true,
  Performance: true,
  PerformanceEntry: true,
  PerformanceMark: true,
  PerformanceMeasure: true,
  PerformanceObserver: true,
  PerformanceObserverEntryList: true,
  PerformanceResourceTiming: true,
  PerformanceServerTiming: true,
  PeriodicSyncManager: true,
  PermissionStatus: true,
  Permissions: true,
  PushManager: true,
  PushSubscription: true,
  PushSubscriptionOptions: true,
  SecurityPolicyViolationEvent: true,
  ServiceWorkerRegistration: true,
  StorageManager: true,
  SubtleCrypto: true,
  SyncManager: true,
  TextDecoder: true,
  TextDecoderStream: true,
  TextEncoder: true,
  TextEncoderStream: true,
  TextMetrics: true,
  TransformStream: true,
  TrustedTypePolicyFactory: true,
  USB: true,
  USBAlternateInterface: true,
  USBConfiguration: true,
  USBConnectionEvent: true,
  USBDevice: true,
  USBEndpoint: true,
  USBInTransferResult: true,
  USBInterface: true,
  USBIsochronousInTransferPacket: true,
  USBIsochronousInTransferResult: true,
  USBIsochronousOutTransferPacket: true,
  USBIsochronousOutTransferResult: true,
  USBOutTransferResult: true,
  UserActivation: true,
  WebAssembly: true,
  WebGL2RenderingContext: true,
  WebGLActiveInfo: true,
  WebGLBuffer: true,
  WebGLFramebuffer: true,
  WebGLProgram: true,
  WebGLQuery: true,
  WebGLRenderbuffer: true,
  WebGLRenderingContext: true,
  WebGLSampler: true,
  WebGLShader: true,
  WebGLShaderPrecisionFormat: true,
  WebGLSync: true,
  WebGLTexture: true,
  WebGLTransformFeedback: true,
  WebGLUniformLocation: true,
  WebGLVertexArrayObject: true,
  WebSocket: true,
  Worker: true,
  WorkerLocation: true,
  WorkerNavigator: true,
  WritableStream: true,
  WritableStreamDefaultWriter: true,
  caches: true,
  close: true,
  crypto: true,
  fonts: true,
  indexedDB: true,
  location: true,
  navigator: true,
  webkitRequestFileSystem: true,
  webkitRequestFileSystemSync: true,
  webkitResolveLocalFileSystemSyncURL: true,
  webkitResolveLocalFileSystemURL: true,
  // Network
  XMLHttpRequestUpload: true,
  XMLHttpRequestEventTarget: true,
  XMLHttpRequest: true,
  // Other
  Function: () => () => {
    // noop
  },
  eval: true,
  importScripts: true,
};

function clobber(object: object, denylist: Denylist) {
  let target = object;
  do {
    Object.getOwnPropertyNames(target)
      .filter((key) => denylist[key])
      // eslint-disable-next-line no-loop-func
      .forEach((key) => {
        try {
          Object.defineProperty(target, key, {
            value: denylist[key] === true ? undefined : denylist[key],
            configurable: false,
            enumerable: false,
            writable: false,
          });
          // eslint-disable-next-line no-empty
        } catch (_) {}
      });
    target = Object.getPrototypeOf(target);
  } while (target !== Object.prototype);
}

export const apply = (workerGlobalScope: object, denylist: Denylist = builtIns) => {
  clobber(workerGlobalScope, denylist);
};
