/**
 * A descriptor for selecting the data a field would like to receive during
 * autocomplete. This attribute is modeled off of a limited set of the autocomplete
 * values supported in browsers.
 *
 * @see https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens
 */
export interface Autocomplete {
  /**
   * The contact information “group” the autocomplete data should be sourced from.
   */
  group?: AutocompleteGroup;
  /**
   * The type of data that should be inserted into a field supporting autocomplete.
   */
  field: AutocompleteField;
}

export type AutocompleteGroup = 'shipping' | 'billing';

export type AutocompleteField =
  | 'name'
  | 'honorific-prefix'
  | 'given-name'
  | 'additional-name'
  | 'family-name'
  | 'honorific-suffix'
  | 'nickname'
  | 'username'
  | 'new-password'
  | 'current-password'
  | 'one-time-code'
  | 'organization-title'
  | 'organization'
  | 'street-address'
  | 'address-line1'
  | 'address-line2'
  | 'address-line3'
  | 'address-level4'
  | 'address-level3'
  | 'address-level2'
  | 'address-level1'
  | 'country'
  | 'country-name'
  | 'postal-code'
  | 'cc-name'
  | 'cc-given-name'
  | 'cc-additional-name'
  | 'cc-family-name'
  | 'cc-number'
  | 'cc-exp'
  | 'cc-exp-month'
  | 'cc-exp-year'
  | 'cc-csc'
  | 'cc-type'
  | 'transaction-currency'
  | 'transaction-amount'
  | 'language'
  | 'bday'
  | 'bday-day'
  | 'bday-month'
  | 'bday-year'
  | 'sex'
  | 'url'
  | 'photo'
  | 'tel'
  | 'tel-country-code'
  | 'tel-national'
  | 'tel-area-code'
  | 'tel-local'
  | 'tel-local-prefix'
  | 'tel-local-suffix'
  | 'tel-extension'
  | 'email'
  | 'impp'
  | 'home tel'
  | 'home tel-country-code'
  | 'home tel-national'
  | 'home tel-area-code'
  | 'home tel-local'
  | 'home tel-local-prefix'
  | 'home tel-local-suffix'
  | 'home tel-extension'
  | 'home email'
  | 'home impp'
  | 'work tel'
  | 'work tel-country-code'
  | 'work tel-national'
  | 'work tel-area-code'
  | 'work tel-local'
  | 'work tel-local-prefix'
  | 'work tel-local-suffix'
  | 'work tel-extension'
  | 'work email'
  | 'work impp'
  | 'mobile tel'
  | 'mobile tel-country-code'
  | 'mobile tel-national'
  | 'mobile tel-area-code'
  | 'mobile tel-local'
  | 'mobile tel-local-prefix'
  | 'mobile tel-local-suffix'
  | 'mobile tel-extension'
  | 'mobile email'
  | 'mobile impp'
  | 'fax tel'
  | 'fax tel-country-code'
  | 'fax tel-national'
  | 'fax tel-area-code'
  | 'fax tel-local'
  | 'fax tel-local-prefix'
  | 'fax tel-local-suffix'
  | 'fax tel-extension'
  | 'fax email'
  | 'fax impp'
  | 'pager tel'
  | 'pager tel-country-code'
  | 'pager tel-national'
  | 'pager tel-area-code'
  | 'pager tel-local'
  | 'pager tel-local-prefix'
  | 'pager tel-local-suffix'
  | 'pager tel-extension'
  | 'pager email'
  | 'pager impp';
