# Sync our `helper.docs.ts` from `checkout-ui-extensions` to `checkout-ui-extensions-react`
chmod u+rw ../checkout-ui-extensions-react/src/helper.docs.ts
cp ./src/helper.docs.ts ../checkout-ui-extensions-react/src/helper.docs.ts
sed -i "1s;^;/*\n * DO NOT EDIT THIS FILE MANUALLY, it will be overidden by the docs build process.\n * It's auto-generated when 'build:api-docs' is run.\n * The source of this file can be edited in 'packages/checkout-ui-extensions/src/helper.docs.ts'.\n * This should be checked into source control.\n */\n\n;" ../checkout-ui-extensions-react/src/helper.docs.ts
## No really, don't edit this file. It's auto-generated.
chmod 0444 ../checkout-ui-extensions-react/src/helper.docs.ts

COMPILE_DOCS="yarn tsc --project docs/tsconfig.docs.json --types react,node --moduleResolution node  --target esNext  --module commonjs && yarn generate-docs --overridePath ./docs/typeOverride.json --input ./src ../checkout-ui-extensions-react/src --output ./docs/generated"
COMPILE_STATIC_PAGES="yarn tsc docs/staticPages/*.doc.ts --types react --moduleResolution node  --target esNext  --module commonjs && yarn generate-docs --isLandingPage --input ./docs/staticPages --output ./docs/generated"

eval $COMPILE_DOCS && eval $COMPILE_STATIC_PAGES
build_exit=$?

# TODO: get generate-docs to stop requiring JS files:
# https://github.com/Shopify/generate-docs#important-note
find ../ -name '*.doc.js' -exec rm -r {} \;
rm ./src/helper.docs.js
rm ../checkout-ui-extensions-react/src/helper.docs.js

if [ $build_exit -ne 0 ]; then
  echo "** Failed to generate docs"
  echo "See https://checkout.docs.shopify.io/docs/referencedocs/web/extensions/docs"
  exit $build_exit
fi


if [ -n "$SPIN" ]; then
  if [ -n "$SPIN_SHOPIFY_DEV_SERVICE_FQDN" ]; then
    cp ./docs/generated/* ~/src/github.com/Shopify/shopify-dev/db/data/docs/templated_apis/checkout_extensions/
    rsync -a --delete ./docs/screenshots/ ~/src/github.com/Shopify/shopify-dev/app/assets/images/templated-apis-screenshots/checkout-ui-extensions
    cd ~/src/github.com/Shopify/shopify-dev
    restart
    echo "Docs: https://$SPIN_SHOPIFY_DEV_SERVICE_FQDN/docs/api/checkout-ui-extensions"
  else
    echo "If you include shopify-dev in your Spin constellation, this will automatically copy ./docs/generated to shopify-dev"
  fi
else
  echo "Not copying docs to shopify-dev because we're not in Spin"
fi
