API_VERSION=$1
DOCS_PATH=docs/surfaces/checkout
SRC_PATH=src/surfaces/checkout
COMPONENTS_DIR=src/surfaces/checkout/components

fail_and_exit() {
  echo "** Failed to generate docs"
  echo "See https://vault.shopify.io/page/Extension-Docs~SkgE.md"
  exit $1
}

run_sed() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    # WARNING: do not synchronize this with checkout-web
    sed -Ei '' "$1" "$2"
  else
    # Linux and other Unix-like systems
    sed -ri "$1" "$2"
  fi
}

if [ "$API_VERSION" = "unstable" ]; then
  echo "Publishing docs for the 'unstable' checkout UI extensions API is not supported. You must specify a calver version YYYY-MM or YYYY-MM-rc (for a release candidate)."
  exit 1;
fi

if [ -z $API_VERSION ]
then
  echo "You must specify a calver version YYYY-MM or YYYY-MM-rc (for a release candidate)."
  exit 1;
else
  echo "Building docs for '$API_VERSION' checkout UI extensions API."
fi

COMPILE_DOCS="yarn generate-docs --overridePath ./$DOCS_PATH/typeOverride.json --input ./$SRC_PATH --output ./$DOCS_PATH/generated"

# Copy all .d.ts files in components directory to .ts files so they can be picked up by the generate-docs tool
echo "Copying .d.ts files to temporary .ts files..."
TEMP_FILES=()
for dts_file in $COMPONENTS_DIR/*.d.ts; do
  if [ -f "$dts_file" ]; then
    # Skip components-shared.d.ts
    if [[ "$dts_file" == *"components-shared.d.ts" ]]; then
      continue
    fi
    # Convert .d.ts to .ts (e.g., components.d.ts -> components.ts)
    temp_file="${dts_file%.d.ts}.ts"
    cp "$dts_file" "$temp_file"
    TEMP_FILES+=("$temp_file")
  fi
done

if echo "$PWD" | grep -q '\checkout-web'; then
  # We are generating docs from the private package, which does not have other surfaces aside from checkout
  eval $COMPILE_DOCS
  build_exit=$?
else
  # Other surfaces may have duplicate types that cause issues with documentation generation,
  # so we erase their contents and replace them afterwards
  echo "export {}" > src/surfaces/customer-account.ts
  echo "export {}" > src/surfaces/admin.ts
  eval $COMPILE_DOCS
  build_exit=$?
  git checkout HEAD -- src/surfaces/customer-account.ts
  git checkout HEAD -- src/surfaces/admin.ts
fi

# Remove all temporary .ts files that were created from .d.ts files
echo "Removing temporary .ts files..."
for temp_file in "${TEMP_FILES[@]}"; do
  if [ -f "$temp_file" ]; then
    rm -f "$temp_file"
  fi
done

if [ $build_exit -ne 0 ]; then
  fail_and_exit $build_exit
fi

# Make sure https://shopify.dev URLs are relative.
# See https://github.com/Shopify/generate-docs/issues/181
run_sed 's/https:\/\/shopify.dev//gi' ./$DOCS_PATH/generated/generated_docs_data_v2.json
sed_exit=$?
if [ $sed_exit -ne 0 ]; then
  fail_and_exit $sed_exit
fi

# Generate targets.json (extension targets + APIs + components mapping)
node ./$DOCS_PATH/build-docs-targets-json.mjs $API_VERSION
targets_exit=$?
if [ $targets_exit -ne 0 ]; then
  fail_and_exit $targets_exit
fi

echo ""
echo "Generated docs at:"
echo "  Checkout UI extensions: $PWD/$DOCS_PATH/generated"
echo "  targets.json: $PWD/$DOCS_PATH/generated/targets.json"
echo ""

copy_generated_docs_to_shopify_dev() {
# Copy the generated docs to shopify-dev
if [ -d $SHOPIFY_DEV_PATH ]; then
  SHOPIFY_DEV_DEST=$SHOPIFY_DEV_PATH/areas/platforms/shopify-dev/db/data/docs/templated_apis/checkout_extensions/$API_VERSION
  mkdir -p $SHOPIFY_DEV_DEST
  cp ./$DOCS_PATH/generated/* $SHOPIFY_DEV_DEST

  # Also copy the targets.json generated by build-docs-targets-json.mjs
  GENERATED_TARGETS=./$DOCS_PATH/generated/targets.json
  if [ -f "$GENERATED_TARGETS" ]; then
    cp "$GENERATED_TARGETS" $SHOPIFY_DEV_DEST/targets.json
  fi

  # Replace 'latest' with the exact API version in relative doc links
  run_sed \
    "s/\/docs\/api\/checkout-ui-extensions\/latest/\/docs\/api\/checkout-ui-extensions\/$API_VERSION/gi" \
    "$SHOPIFY_DEV_DEST/generated_docs_data_v2.json"
  sed_exit=$?
  if [ $sed_exit -ne 0 ]; then
    fail_and_exit $sed_exit
  fi

  echo "Docs: https://shopify-dev.shop.dev/docs/api/checkout-ui-extensions"
else
  echo "Not copying docs to shopify-dev because it was not found at $SHOPIFY_DEV_PATH."
fi
}

# Try candidate paths for shopify-dev / world repo in order of preference
for SHOPIFY_DEV_PATH in \
  "$HOME/world/trees/root/src" \
  "../../../shopify-dev" \
  "$HOME/src/github.com/Shopify/shopify-dev"; do
  if [ -d "$SHOPIFY_DEV_PATH" ]; then
    copy_generated_docs_to_shopify_dev
    break
  fi
done

if [ ! -d "$SHOPIFY_DEV_PATH" ]; then
  echo "Not copying docs to shopify-dev because no repo was found."
fi
