api_version = "2026-04"

[[extensions]]
type = "ui_extension"
name = "Your checkout extension"
handle = "checkout-ui"
uid = "fddfc370-27c7-c30f-4ee0-a927194e2accadefd40c"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./Extension.jsx"
