api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Your checkout extension"
handle = "checkout-ui"

  [[extensions.targeting]]
  target = "purchase.checkout.block.render"
  module = "./Extension.jsx"

