# ...

# The metafields for the extension
[[extensions.metafields]]
namespace = "my-namespace"
key = "my-key-1"

[[extensions.metafields]]
namespace = "my-namespace"
key = "my-key-2"

# app owned metafield
[[extensions.metafields]]
namespace = "$app:my-app-owned-namespace"
key = "my-key-3"

[[extensions.targeting]]
target = "purchase.checkout.actions.render-before"
module = "./Actions.jsx"

  # For the above target, use these metafields
  [[extensions.targeting.metafields]]
  namespace = "my-namespace"
  key = "my-target-key"

[[extensions.targeting]]
target = "purchase.checkout.shipping-option-item.render-after"
module = "./ShippingOptions.jsx"


