export enum ExtensionTargetType {
  PosHomeModalRender = 'pos.home.modal.render',
  PosHomeTileRender = 'pos.home.tile.render',
  PosPurchasePostActionMenuItemRender = 'pos.purchase.post.action.menu-item.render',
  PosPurchasePostActionRender = 'pos.purchase.post.action.render',
  PosPurchasePostBlockRender = 'pos.purchase.post.block.render',
  PosProductDetailsActionMenuItemRender = 'pos.product-details.action.menu-item.render',
  PosProductDetailsActionRender = 'pos.product-details.action.render',
  PosProductDetailsBlockRender = 'pos.product-details.block.render',
  PosOrderDetailsActionMenuItemRender = 'pos.order-details.action.menu-item.render',
  PosOrderDetailsActionRender = 'pos.order-details.action.render',
  PosOrderDetailsBlockRender = 'pos.order-details.block.render',
  PosCustomerDetailsActionMenuItemRender = 'pos.customer-details.action.menu-item.render',
  PosCustomerDetailsActionRender = 'pos.customer-details.action.render',
  PosCustomerDetailsBlockRender = 'pos.customer-details.block.render',
  PosDraftOrderDetailsActionMenuItemRender = 'pos.draft-order-details.action.menu-item.render',
  PosDraftOrderDetailsActionRender = 'pos.draft-order-details.action.render',
  PosDraftOrderDetailsBlockRender = 'pos.draft-order-details.block.render',
  PosTransactionCompleteObserve = 'pos.transaction-complete.event.observe',
  PosCashTrackingSessionStartObserve = 'pos.cash-tracking-session-start.event.observe',
  PosCashTrackingSessionCancelObserve = 'pos.cash-tracking-session-cancel.event.observe',
  PosCashTrackingSessionCompleteObserve = 'pos.cash-tracking-session-complete.event.observe',
  PosPrepareReceiptInject = 'pos.prepare-receipt.event.inject',
  PosCartUpdateObserve = 'pos.cart-update.event.observe',
}

export enum TargetLink {
  PosHomeModalRender = '[pos.home.modal.render](/docs/api/pos-ui-extensions/targets/smart-grid/pos-home-modal-render)',
  PosHomeTileRender = '[pos.home.tile.render](/docs/api/pos-ui-extensions/targets/smart-grid/pos-home-tile-render)',
  PosPurchasePostActionMenuItemRender = '[pos.purchase.post.action.menu-item.render](/docs/api/pos-ui-extensions/targets/post-purchase/pos-purchase-post-action-menu-item-render)',
  PosPurchasePostActionRender = '[pos.purchase.post.action.render](/docs/api/pos-ui-extensions/targets/post-purchase/pos-purchase-post-action-render)',
  PosPurchasePostBlockRender = '[pos.purchase.post.block.render](/docs/api/pos-ui-extensions/targets/post-purchase/pos-purchase-post-block-render)',
  PosProductDetailsActionMenuItemRender = '[pos.product-details.action.menu-item.render](/docs/api/pos-ui-extensions/targets/product-details/pos-product-details-action-menu-item-render)',
  PosProductDetailsActionRender = '[pos.product-details.action.render](/docs/api/pos-ui-extensions/targets/product-details/pos-product-details-action-render)',
  PosProductDetailsBlockRender = '[pos.product-details.block.render](/docs/api/pos-ui-extensions/targets/product-details/pos-product-details-block-render)',
  PosOrderDetailsActionMenuItemRender = '[pos.order-details.action.menu-item.render](/docs/api/pos-ui-extensions/targets/order-details/pos-order-details-action-menu-item-render)',
  PosOrderDetailsActionRender = '[pos.order-details.action.render](/docs/api/pos-ui-extensions/targets/order-details/pos-order-details-action-render)',
  PosOrderDetailsBlockRender = '[pos.order-details.block.render](/docs/api/pos-ui-extensions/targets/order-details/pos-order-details-block-render)',
  PosCustomerDetailsActionMenuItemRender = '[pos.customer-details.action.menu-item.render](/docs/api/pos-ui-extensions/targets/customer-details/pos-customer-details-action-menu-item-render)',
  PosCustomerDetailsActionRender = '[pos.customer-details.action.render](/docs/api/pos-ui-extensions/targets/customer-details/pos-customer-details-action-render)',
  PosCustomerDetailsBlockRender = '[pos.customer-details.block.render](/docs/api/pos-ui-extensions/targets/customer-details/pos-customer-details-block-render)',
  PosDraftOrderDetailsActionMenuItemRender = '[pos.draft-order-details.action.menu-item.render](/docs/api/pos-ui-extensions/targets/draft-order-details/pos-draft-order-details-action-menu-item-render)',
  PosDraftOrderDetailsActionRender = '[pos.draft-order-details.action.render](/docs/api/pos-ui-extensions/targets/draft-order-details/pos-draft-order-details-action-render)',
  PosDraftOrderDetailsBlockRender = '[pos.draft-order-details.block.render](/docs/api/pos-ui-extensions/targets/draft-order-details/pos-draft-order-details-block-render)',
  PosTransactionCompleteObserve = '[pos.transaction-complete.event.observe](/docs/api/pos-ui-extensions/targets/post-purchase/pos-transaction-complete-observe)',
  PosCashTrackingSessionStartObserve = '[pos.cash-tracking-session-start.event.observe](/docs/api/pos-ui-extensions/targets/cash-tracking/pos-cash-tracking-session-start-observe)',
  PosCashTrackingSessionCancelObserve = '[pos.cash-tracking-session-cancel.event.observe](/docs/api/pos-ui-extensions/targets/cash-tracking/pos-cash-tracking-session-cancel-observe)',
  PosCashTrackingSessionCompleteObserve = '[pos.cash-tracking-session-complete.event.observe](/docs/api/pos-ui-extensions/targets/cash-tracking/pos-cash-tracking-session-complete-observe)',
  PosPrepareReceiptInject = '[pos.prepare-receipt.event.inject](/docs/api/pos-ui-extensions/targets/prepare-receipt-inject)',
  PosCartUpdateObserve = '[pos.cart-update.event.observe](/docs/api/pos-ui-extensions/targets/cart-update-observe)',
}
