export type StandardComponents =
  | 'Badge'
  | 'Banner'
  | 'Box'
  | 'Button'
  | 'CameraScanner'
  | 'Choice'
  | 'ChoiceList'
  | 'Clickable'
  | 'DateField'
  | 'DatePicker'
  | 'DateSpinner'
  | 'Divider'
  | 'EmailField'
  | 'Heading'
  | 'Icon'
  | 'Image'
  | 'Modal'
  | 'NumberField'
  | 'Page'
  | 'POSBlock'
  | 'PosBlock' // Case is important in 2025-10
  | 'QRCode'
  | 'QrCode' // Case is important in 2025-10
  | 'Route'
  | 'Router'
  | 'ScrollBox'
  | 'SearchField'
  | 'Section'
  | 'Stack'
  | 'Text'
  | 'TextArea'
  | 'TextField'
  | 'Tile'
  | 'TimeField'
  | 'TimePicker';

export default StandardComponents;
