name: Changelog Reminder

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 2023-04
      - 2023-07
      - 2023-10
      - 2024-01
      - 2024-04
      - 2024-07
      - 2024-10
      - unstable
      - 20[0-9][0-9]-[01][1470]
    paths:
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - '!*.test.*'
      - '!*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  remind:
    name: Changeset Reminder
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ !github.event.pull_request.draft && !startsWith(github.head_ref, 'changeset-release/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/changelog-reminder-action@v2
        with:
          changelogRegex: "\\.changeset"
          message: >
            We detected some changes in `packages/*/package.json` or `packages/*/src`, and there are no updates in the `.changeset` directory.
            If the changes are user-facing and should cause a version bump, run `yarn changeset` to track your changes and include them in the next release CHANGELOG.
            If you are making simple updates to repo configuration, examples, or documentation, you do not need to add a changeset.
