name: CI

on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/prepare

      - id: typescript-cache
        name: Restore TypeScript cache
        uses: actions/cache@v4
        with:
          path: |
            packages/*/build/ts
            packages/*/build/*.tsbuildinfo
          key: ${{ runner.os }}-typescript-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-typescript-v1-

      - name: Type check
        run: yarn type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare

      - id: jest-cache
        name: Restore jest cache
        uses: actions/cache@v1
        with:
          path: .loom/cache/jest/
          key: ${{ runner.os }}-jest-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-jest-v1-

      - name: Test
        run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/prepare

      - id: eslint-cache
        name: Restore ESLint cache
        uses: actions/cache@v4
        with:
          path: .loom/cache/eslint
          key: ${{ runner.os }}-eslint-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-eslint-v1-

      - name: Lint
        run: yarn lint

  yarn-lockfile-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/prepare

      - name: yarn.lock check
        run: |
          yarn
          if [ -n "$(git status --porcelain yarn.lock)" ]; then
            echo "yarn.lock has changed"
            exit 1
          fi
