name: CI

on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare

      - id: typescript-cache
        name: Restore TypeScript cache
        uses: actions/cache@v1
        with:
          path: |
            packages/*/build/ts
            packages/*/build/*.tsbuildinfo
          key: ${{ runner.os }}-typescript-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-typescript-v1-

      - name: Type check
        run: yarn type-check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare

      - id: eslint-cache
        name: Restore ESLint cache
        uses: actions/cache@v1
        with:
          path: .loom/cache/eslint
          key: ${{ runner.os }}-eslint-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-eslint-v1-

      - name: Lint
        run: yarn lint

  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare

      - id: test-build
        name: Build docs locally to ensure they can be built in CI
        run: yarn docs:admin
