name: Internal Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - internal

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  internal-snapshot:
    name: Internal Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare

      - name: Create an .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Deploy snapshot versions
        run: yarn run deploy:internal
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
