name: Snapit

on:
  issue_comment:
    types:
      - created

jobs:
  snapit:
    name: Snapit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare

      - name: Create snapshot
        uses: Shopify/snapit@allow-post-install-script
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          post_install_script: yarn changeset:exit-pre-mode
          build_script: yarn build
          comment_command: /snapit
